[package]
name = "raytracer"
version = "0.1.0"
authors = ["Tudor Tomescu <tudor.tomescu97@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23"
log = "0.4"