filepath: "/home/tuydore/repositories/raytracer/results/test_yaml.jpg"
threads: 2

camera:
  origin: [30.0, 30.0, 15.0]
  gaze: [-1.0, -1.0, -0.5]
  up: [-0.5, -0.5, 2.0]
  fov: [18.0, 32.0]
  density: 200.0
  vop: air

volumes:
  air:
    ior: 1.0
  glass:
    ior: 1.5

surfaces:
  - type: checkerboard
    origin: [0.0, 0.0, 0.0]
    normal: [0.0, 0.0, 1.0]
    orientation: [0.0, 1.0, 0.0]
    sop:
      light: [255, 255, 255]
    tile_size: 2.0
    vop_above: air
    vop_below: air
  
  - type: sphere
    center: [6.0, 6.0, 2.0]
    radius: 2.0
    sop:
      refract: null
    vop_above: air
    vop_below: glass

  - type: sphere
    center: [0.0, 0.0, 2.0]
    radius: 2.0
    sop:
      light: [94, 39, 80]
    vop_above: air
    vop_below: glass

  - type: sphere
    center: [0.0, 6.0, 2.0]
    radius: 2.0
    sop:
      reflect: null
    vop_above: air
    vop_below: glass

  - type: sphere
    center: [6.0, 0.0, 2.0]
    radius: 2.0
    sop:
      reflect: null
    vop_above: air
    vop_below: glass
