filepath: "/home/tuydore/repositories/raytracer/results/test_yaml.jpg"

camera:
  origin: [1.0, 1.0, 10.0]
  gaze: [0.0, 0.0, -1.0]
  up: [1.0, 0.0, 0.0]
  fov: [30.0, 30.0]
  density: 20.0
  vop: air

volumes:
  air:
    ior: 1.0
  glass:
    ior: 1.7

surfaces:
  - type: checkerboard
    origin: [0.0, 0.0, 0.0]
    normal: [0.0, 0.0, 1.0]
    orientation: [0.0, 1.0, 0.0]
    sop:
      light: [255, 255, 255]
    tile_size: 2.0
    vop_above: air
    vop_below: air

  - type: sphere
    center: [0.0, 0.0, 2.0]
    radius: 1.0
    sop:
      refract: null
    vop_above: air
    vop_below: glass